### ISSUE TITLE
Unable to run gradle

### ISSUE THREAD

**Issue by pfateev** [ssaran8/Team-Thrive#16]
I tried the command `./gradlew runSpark` and I get the following message:
`./gradlew: command not found`
I'm on macOS and I was attempting the command from the `backend` directory

I installed gradle just in case as well, but that didn't do anything.

I am able to install and run the frontend fine.

**Comment by Lawqup** [comment]
I'm having a similar issue. Try `chmod +x ./gradlew` to make the file executable. When I do that and run the command again, I get this:

```
➜  backend git:(main) ✗ ./gradlew runSpark 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'backend'.
> Could not open proj generic class cache for build file '/home/lawrence/Documents/Code/Homework/CSE403/Team-Thrive/backend/build.gradle' (/home/lawrence/.gradle/caches/6.7/scripts/v5wy4o5bj8m0yv62048tupw5).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 401ms
```

**Comment by pfateev** [comment]
> ./gradlew runSpark

@Lawqup thanks for that – it helped me execute, but I'm actually seeing a different error than you:

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'backend'.
> Could not open proj generic class cache for build file '/Users/pasha/Documents/UW/23wi/403/Team-Thrive/backend/build.gradle' (/Users/pasha/.gradle/caches/6.7/scripts/v5wy4o5bj8m0yv62048tupw5).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 60

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org`

**Comment by royliurl** [comment]
Try setting `distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.2-bin.zip` in `backend\gradle\wrapper\gradle-wrapper.properties`.

**Comment by pfateev** [comment]
> 

This worked for me I think. Thanks
